In [45]:
import pandas as pd
import numpy as np

In [46]:
df = pd.read_csv("student_performance.csv")

In [47]:
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

### How many rows and columns are there in the dataset?

In [48]:
print(df.shape)

(1000000, 6)

### Show the first 10 rows of the dataset.

In [49]:
df.head(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
5,6,13.4,65.1,5.0,97.5,A
6,7,26.1,81.8,5.9,100.0,A
7,8,20.4,100.0,4.0,96.1,A
8,9,11.7,100.0,8.2,69.8,C
9,10,18.8,67.6,6.0,80.3,B

### Show the last 10 rows of the dataset.

In [50]:
df.tail(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
999990,999991,15.4,82.8,4.0,86.9,A
999991,999992,30.0,87.4,6.7,100.0,A
999992,999993,26.3,84.6,4.5,100.0,A
999993,999994,20.7,82.4,5.5,99.1,A
999994,999995,15.1,77.0,9.2,80.5,B
999995,999996,18.0,95.5,4.8,100.0,A
999996,999997,15.7,82.7,6.7,88.3,A
999997,999998,14.2,85.1,5.8,87.9,A
999998,999999,25.3,90.0,5.3,100.0,A
999999,1000000,18.3,84.6,4.1,100.0,A

### What are the column names in the dataset?

In [51]:
print(list[df.columns])

list[Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')]

### What is the maximum value of weekly_self_study_hours?

In [52]:
# df[df['weekly_self_study_hours'] == df['weekly_self_study_hours'].max()]
df['weekly_self_study_hours'].max()

40.0

### Which student studied the most hours in a week?

In [53]:
df[df['weekly_self_study_hours'] == df['weekly_self_study_hours'].max()]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
209,210,40.0,68.1,6.7,100.0,A
2895,2896,40.0,75.7,4.2,100.0,A
15843,15844,40.0,99.5,8.0,100.0,A
18851,18852,40.0,91.7,7.0,100.0,A
20126,20127,40.0,94.1,3.0,100.0,A
...,...,...,...,...,...,...
971477,971478,40.0,74.2,7.7,100.0,A
973306,973307,40.0,90.0,6.2,100.0,A
974300,974301,40.0,78.8,2.5,100.0,A
976629,976630,40.0,93.9,7.0,100.0,A
980167,980168,40.0,82.6,7.2,100.0,A

### Show the top 5 students by weekly_self_study_hours.

In [54]:
df.sort_values('weekly_self_study_hours',ascending = False,).head(5)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
779223,779224,40.0,76.1,6.4,100.0,A
891941,891942,40.0,72.6,8.8,100.0,A
334965,334966,40.0,92.3,5.4,100.0,A
912897,912898,40.0,100.0,9.1,100.0,A
628230,628231,40.0,93.4,5.2,100.0,A

### Which student has the highest attendance percentage?

In [55]:
df[df['attendance_percentage'] == df['attendance_percentage'].max()]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
7,8,20.4,100.0,4.0,96.1,A
8,9,11.7,100.0,8.2,69.8,C
18,19,8.6,100.0,9.0,75.4,B
22,23,15.5,100.0,8.5,76.3,B
44,45,4.7,100.0,3.3,55.9,C
...,...,...,...,...,...,...
999919,999920,10.9,100.0,7.9,67.6,C
999921,999922,7.0,100.0,6.9,66.2,C
999931,999932,10.4,100.0,5.8,69.3,C
999938,999939,13.7,100.0,4.3,98.8,A
999939,999940,8.9,100.0,7.8,73.4,B

### Which student has the highest class participation?

In [56]:
stu = df[df['attendance_percentage'] == df['attendance_percentage'].max()].count()[0]
print(stu,"\n")
total = df.shape[0]
percentage = (stu / total) * 100
print(percentage,"percent")

67378

6.737799999999999 percent

/tmp/ipykernel_2988/3195426917.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stu = df[df['attendance_percentage'] == df['attendance_percentage'].max()].count()[0]

### Create a new column score_level
"High" if total_score ≥ 90 , "Medium" if 70 ≤ total_score < 90, "Low" if total_score < 70

In [57]:
def level (x):
    if x>= 90:
        return "High"
    elif x>= 70:
        return "Medium"
    elif x< 70:
        return "Low"

In [58]:
df['score_level'] = df['total_score'].apply(level)
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level
0,1,18.5,95.6,3.8,97.9,A,High
1,2,14.0,80.0,2.5,83.9,B,Medium
2,3,19.5,86.3,5.3,100.0,A,High
3,4,25.7,70.2,7.0,100.0,A,High
4,5,13.4,81.9,6.9,92.0,A,High
...,...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A,High
999996,999997,15.7,82.7,6.7,88.3,A,Medium
999997,999998,14.2,85.1,5.8,87.9,A,Medium
999998,999999,25.3,90.0,5.3,100.0,A,High
999999,1000000,18.3,84.6,4.1,100.0,A,High

### Which student has the highest total_score?

In [63]:
student = df[df['total_score'] == df['total_score'].max()].count()
total = df.shape[0]
percentage = (student/total)*100
percentage

student_id                 26.8121
weekly_self_study_hours    26.8121
attendance_percentage      26.8121
class_participation        26.8121
total_score                26.8121
grade                      26.8121
score_level                26.8121
dtype: float64

### How many students scored exactly 100 in total_score?

In [64]:
len(df[df['total_score']==df['total_score'].max()])

268121

### Make a new column for study efficiency = total_score ÷ weekly_self_study_hours.

In [66]:
df['Efficiency'] = df['total_score']/df['weekly_self_study_hours']
df['Efficiency']

0         5.291892
1         5.992857
2         5.128205
3         3.891051
4         6.865672
            ...
999995    5.555556
999996    5.624204
999997    6.190141
999998    3.952569
999999    5.464481
Name: Efficiency, Length: 1000000, dtype: float64

### Create a new column study_category
"Light" if weekly_self_study_hours < 10,
"Moderate" if 10 ≤ hours ≤ 20,
"Heavy" if hours > 20

In [67]:
def category(study_hours):
    if study_hours<10:
        return 'Light'
    elif study_hours <20:
        return 'Medium'
    else:
        return 'Heavy'

In [69]:
df['Category'] = df['weekly_self_study_hours'].apply(category)
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,score_level,Efficiency,Category
0,1,18.5,95.6,3.8,97.9,A,High,5.291892,Medium
1,2,14.0,80.0,2.5,83.9,B,Medium,5.992857,Medium
2,3,19.5,86.3,5.3,100.0,A,High,5.128205,Medium
3,4,25.7,70.2,7.0,100.0,A,High,3.891051,Heavy
4,5,13.4,81.9,6.9,92.0,A,High,6.865672,Medium
...,...,...,...,...,...,...,...,...,...
999995,999996,18.0,95.5,4.8,100.0,A,High,5.555556,Medium
999996,999997,15.7,82.7,6.7,88.3,A,Medium,5.624204,Medium
999997,999998,14.2,85.1,5.8,87.9,A,Medium,6.190141,Medium
999998,999999,25.3,90.0,5.3,100.0,A,High,3.952569,Heavy
999999,1000000,18.3,84.6,4.1,100.0,A,High,5.464481,Medium